SELECT T1.CENTERID, T1.CUSTACCOUNT, T1.CUSTNAME, T1.PROJECTID, T1.COURSEPRICE, T1.COURSEFEE, T1.PAYABLEAMOUNTPATWAY, T1.ILAACCOUNTAMOUNTPATHWAY AS [Paid By ILA ACCOUNT],
	dbo.GetProduct(T1.PROJECTID) AS [Product], T2.SellerOriginalName AS [EP Incharge], T2.SellerOriginalCode AS Code
FROM VIEWREGISTRATION_LT T1
INNER JOIN [CRM.View_Need] T2
	ON T1.REGISTRATIONID = T2.ContractNo
WHERE T1.CENTERID IN ('OLA-HCMC1', 'OLA-HCMC2', 'OLA-MT1', 'OLA-VL1')
	AND MONTH(T1.REGISTRATIONDATE) = 2
	AND YEAR(T1.REGISTRATIONDATE) = 2022
	AND T1.REGISTRATIONSTATUS = 2
	AND T1.STUDENTTYPEID IN (5, 6)
	AND T2.IsSale = 1