SELECT T3.ILAGroup, T2.ILADASHBOARDCENTERID AS [ILA Centres], T1.CUSTACCOUNT, T1.CUSTNAME, T1.CURRENTPROJ AS [CURRENT CLASS], T1.CURACTUALENDDATE AS [ACTUALENDATE],
	T1.CURREGISTRATIONID AS [Current Regis ID], T1.NEXTPROJECTID AS [NEXT CLASS], T1.NEXTREGISDATE, T1.NEXTREGISTRATIONID, COUNT(T1.CUSTACCOUNT) AS [Finished],
	COUNT(CASE WHEN T1.NEXTPROJECTID IS NULL THEN T1.CUSTACCOUNT ELSE NULL END) AS [Stopped],
	COUNT(CASE WHEN T1.NEXTPROJECTID IS NOT NULL THEN T1.CUSTACCOUNT ELSE NULL END) AS [Re Enrollment],
	CASE WHEN T5.PRODUCTGROUPID = 'OLA' THEN T5.ILAACCOUNT ELSE 0 END AS [ILA Acc OLA],
	CASE WHEN T5.PRODUCTGROUPID = 'ELT' THEN T5.ILAACCOUNT ELSE 0 END AS [ILA Acc ELT]
FROM [Data.StopAndReEnroll] T1
INNER JOIN [Dim.InventSite] T2
	ON T1.CURCENTERPROJ = T2.SITEID
INNER JOIN [Dim.GroupInventsite] T3
	ON T2.SITEID = T3.SiteID
INNER JOIN [Dim.ProjTable] T4
	ON T1.CURRENTPROJ = T4.PROJID
INNER JOIN VIEW_ILAACCOUNT_CURRENT T5
	ON T1.CUSTACCOUNT = T5.CUSTACCOUNT
WHERE T4.ILAPRODUCTGROUPID = 'OLA-EY'
	AND T1.CURDATEKEY BETWEEN 20220301 AND 20220331
GROUP BY T3.ILAGroup, T2.ILADASHBOARDCENTERID, T1.CUSTACCOUNT, T1.CUSTNAME, T1.CURRENTPROJ, T1.CURACTUALENDDATE,
	T1.CURREGISTRATIONID, T1.NEXTPROJECTID, T1.NEXTREGISDATE, T1.NEXTREGISTRATIONID,
	CASE WHEN T5.PRODUCTGROUPID = 'OLA' THEN T5.ILAACCOUNT ELSE 0 END,
	CASE WHEN T5.PRODUCTGROUPID = 'ELT' THEN T5.ILAACCOUNT ELSE 0 END